// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEGgFv5ygaT29wQyyXaFiTFibf5mFeYok',
    appId: '1:578933238318:web:14fd1583391f552aa7cdbf',
    messagingSenderId: '578933238318',
    projectId: 'loggin-875bd',
    authDomain: 'loggin-875bd.firebaseapp.com',
    storageBucket: 'loggin-875bd.appspot.com',
    measurementId: 'G-7Z94EB3K28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCaTiQTrPIwc7F_3YaiGcGEbBoHIPYGqkg',
    appId: '1:578933238318:android:2b7334797ad86257a7cdbf',
    messagingSenderId: '578933238318',
    projectId: 'loggin-875bd',
    storageBucket: 'loggin-875bd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPMSWo2tZXj3Rwg4AuY9XESDq-_hXlG9M',
    appId: '1:578933238318:ios:922f85043330a296a7cdbf',
    messagingSenderId: '578933238318',
    projectId: 'loggin-875bd',
    storageBucket: 'loggin-875bd.appspot.com',
    androidClientId: '578933238318-2a1ujh984glib7ev7g6aklushqa1d6fe.apps.googleusercontent.com',
    iosClientId: '578933238318-t2gl7ebs4sf2eciq8dsqsic5n4l7mvj3.apps.googleusercontent.com',
    iosBundleId: 'com.example.senecaFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPMSWo2tZXj3Rwg4AuY9XESDq-_hXlG9M',
    appId: '1:578933238318:ios:c231da183461d6e3a7cdbf',
    messagingSenderId: '578933238318',
    projectId: 'loggin-875bd',
    storageBucket: 'loggin-875bd.appspot.com',
    androidClientId: '578933238318-2a1ujh984glib7ev7g6aklushqa1d6fe.apps.googleusercontent.com',
    iosClientId: '578933238318-6122oeaomvpu8t51bnitjbuvtci83aia.apps.googleusercontent.com',
    iosBundleId: 'com.example.senecaFlutter.RunnerTests',
  );
}
